import { Movie } from "@/components/reducer";
import Head from "next/head";
import { useRouter } from 'next/router'
import { getData } from "../api/movies";

export async function getStaticProps(context: any) {
    const { params } = context;
    const movieId = params.id;
    const data = await getData();
    
    const movie = data.find((item: Movie) => item.id === movieId);

    return {
      props: { 
        movie
      }
    };
  }

  
export async function getStaticPaths() {
    let response = await getData();
    const paths = response.map((movieId: {id: string}) => {

        return {
            params: {
                id: `${movieId.id}`
            }
        }
    })
  
    return { paths, fallback: false };
  }

const MovieDetail = ({movie}: any) => {
    const router = useRouter();
    
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main>
                <button onClick={() => router.push("/")}>Go Back to home page</button>
                {!movie && <p>Loading...</p>}
                {
                    movie && <>
                        <h1 className="movie-title">{movie.title}</h1>
                        <div className="movie-image-wrapper">
                            <img src={movie.imageUrl} alt="" />
                        </div>
                        <div className="movie-directors">
                            <h3>Directors</h3>
                            <ul>
                                {
                                    movie.director.map((item: string, index: number) => <li key={"director-"+index}>{item}</li>)
                                }
                            </ul>
                        </div>
                        <div className="movie-actors">
                            <h3>Actors</h3>
                            <ul>
                                {
                                    movie.actors.map((item: string, index: number) => <li key={"actor-"+index}>{item}</li> )
                                }
                            </ul>
                        </div>
                        <p className="movie-description">{movie.description}</p>
                    </>
                }
            </main>
        </>
    );
}
 
export default MovieDetail;